In [20]:
import numpy as np

from sklearn import datasets

from sklearn.linear_model import LinearRegression

In [25]:
# 数据查看
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

X=data
y=target
X.shape

(506, 13)

In [29]:
# 数据拆分
index = np.arange(506)
np.random.shuffle(index)
train_index = index[:405]
test_index = index[405:]

In [30]:
X_train = X[train_index]
X_test = X[test_index]
display(X_train.shape,X_test.shape)

(405, 13)

(101, 13)

In [31]:
y_train = y[train_index]
y_test = y[test_index]
display(y_train.shape,y_test.shape)

(405,)

(101,)

In [34]:
# 数据建模
model = LinearRegression(fit_intercept = True)
model.fit(X_train,y_train)

display(model.coef_,model.intercept_)
# 别忘了还有“_”

array([-8.18076203e-02,  3.20771141e-02,  1.99691918e-02,  2.32331081e+00,
       -1.38058335e+01,  4.98060559e+00, -6.33940063e-03, -1.17825537e+00,
        2.31402831e-01, -1.21792235e-02, -9.12823630e-01,  8.90554032e-03,
       -4.21425191e-01])

np.float64(24.98662503546322)

In [37]:
# 模型检验
y_ = model.predict(X_test).round(2) #保留两位
y_[:30]

array([25.  , 20.12, 29.24, 19.62, 17.03,  6.67, 36.26, 15.57, 21.  ,
       23.09, 20.61, 30.67, 27.7 ,  6.15, 28.18, 44.65, 22.66,  2.16,
       19.5 , 32.91, 16.82,  7.89, 20.32,  5.52, 26.1 , 19.69,  9.58,
       20.28, 22.06, 18.87])

In [38]:
y_test[:30]

array([24.6, 16.7, 23.5, 18.9, 14.9, 10.4, 46.7, 11.7, 21.2, 16.5, 20. ,
       31.5, 24.3,  8.4, 24.1, 50. , 24.7,  8.8, 21.8, 33.2, 20.8,  8.5,
       24.3, 13.8, 22.1, 17.7,  8.7, 18.8, 20.6, 14.1])

In [39]:
# 模型评估
model.score(X_test,y_test)

0.6790542371828436

In [40]:
model.score(X_train,y_train)

0.750736959514607

训练数据的拟合能力大于测试数据的拟合能力